package View;
import Controller.*;
import Model.*;
import Utilerias.interfacex;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author root4142
 */
public class frmExistencia extends javax.swing.JInternalFrame {
    private interfacex inter=new interfacex();
    private boolean bod=false,art=false;
    private Vector<JTextField> txtCampos=new Vector<>();
    private ControlBodega controlBodega=new ControlBodega();
    private ControlArticulo controlArticulo=new ControlArticulo();
    private ControlExistencia controlExistencia=new ControlExistencia();
    private Bodega bodega;
    private Articulo articulo;
    private Existencia existencia;
    
    public frmExistencia() {
        initComponents();
        txtCampos.add(txtBodegaID);
        txtCampos.add(txtNombreAticulo);
        txtCampos.add(txtArticuloID);
        txtCampos.add(txtNombreBodega);
        txtCampos.add(txtCantidad);
        txtBodegaID.grabFocus();
    }
    private void Limpiar_Campos(){
        for (JTextField o : txtCampos) {
            o.setText("");
        }
        bod=false;art=false;
        txtBodegaID.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreAticulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBodegaID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnSelArt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNombreBodega = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtArticuloID = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnSelBod = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setTitle("Formulario de Consulta de Existencia de Articulos.");
        setToolTipText("");
        setFrameIcon(null);
        setName("frmExistencia"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreAticulo.setEditable(false);
        txtNombreAticulo.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreAticulo.setName("Nombre"); // NOI18N
        getContentPane().add(txtNombreAticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 260, -1));

        jLabel2.setText("ID De Bodega :");
        jLabel2.setName(""); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        txtBodegaID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBodegaID.setName("Codigo"); // NOI18N
        getContentPane().add(txtBodegaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 90, -1));

        jLabel4.setText("Nombre :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        txtCantidad.setEditable(false);
        txtCantidad.setBackground(new java.awt.Color(255, 255, 255));
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setName("Limite"); // NOI18N
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 110, -1));

        btnSelArt.setText("Seleccionar");
        btnSelArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelArtActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 110, -1));

        jLabel10.setText("Existencia :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        txtNombreBodega.setEditable(false);
        txtNombreBodega.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreBodega.setName("Nombre"); // NOI18N
        getContentPane().add(txtNombreBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 260, -1));

        jLabel6.setText("Nombre :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel3.setText("ID Del Articulo :");
        jLabel3.setName(""); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        txtArticuloID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtArticuloID.setName("Codigo"); // NOI18N
        getContentPane().add(txtArticuloID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 110, -1));

        btnSelBod.setText("Seleccionar");
        btnSelBod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelBodActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelBod, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, -1));

        btnConsultar.setText("Cosultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 110, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-428)/2, (screenSize.height-315)/2, 428, 315);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSelArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelArtActionPerformed
        int x=-1;
        try {
            x = Integer.parseInt(txtArticuloID.getText());
            articulo=new Articulo();
            articulo=controlArticulo.seekArticulo(x);
            if(articulo!=null){
                txtNombreAticulo.setText(articulo.getNombre());
                btnCancelar.grabFocus();
                art = true;
            }
            else{
                art=false;
                txtArticuloID.grabFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe de ingresar un valor numerico", "Error", JOptionPane.ERROR_MESSAGE);
            txtArticuloID.grabFocus();
        }
    }//GEN-LAST:event_btnSelArtActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Limpiar_Campos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSelBodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelBodActionPerformed
        int x=-1;
        try {
            x= Integer.parseInt(txtBodegaID.getText());
            bodega=new Bodega();
            bodega=controlBodega.seekBodega(x);
            if(bodega!=null){
                txtNombreBodega.setText(bodega.getNombre());
                txtArticuloID.grabFocus();
                bod = true;
            }
            else{
                bod=false;
                txtBodegaID.grabFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe de ingresar un valor numerico", "Error", JOptionPane.ERROR_MESSAGE);
            txtBodegaID.grabFocus();
        }
    }//GEN-LAST:event_btnSelBodActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if(!bod){
            JOptionPane.showMessageDialog(rootPane, "Debe de validar primero el ID de la Bodega", "Error", JOptionPane.ERROR_MESSAGE);
            btnSelBod.grabFocus();
        }
        else if(!art){
            JOptionPane.showMessageDialog(rootPane, "Debe de validar primero el ID de la Articulo", "Error", JOptionPane.ERROR_MESSAGE);
            btnSelArt.grabFocus();
        }
        else{
            existencia=new Existencia();
            existencia=controlExistencia.seekExistencia(bodega.getBodegaID(),articulo.getArticuloID());
            if(existencia!=null){
                txtCantidad.setText(existencia.getCantidad()+"");
            }
            else{
                txtCantidad.setText("0");
            }
            btnCancelar.grabFocus();
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnSelArt;
    private javax.swing.JButton btnSelBod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtArticuloID;
    private javax.swing.JTextField txtBodegaID;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombreAticulo;
    private javax.swing.JTextField txtNombreBodega;
    // End of variables declaration//GEN-END:variables
}
