package View;
import Controller.*;
import Model.*;
import Utilerias.interfacex;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author root4142
 */
public class frmFactura extends javax.swing.JInternalFrame {
    private interfacex inter=new interfacex();
    private Vector<JTextField> txtCampos=new Vector<>();
    private Vector<JLabel> lblLabels=new Vector<>();
    private Vector<FacturaDet> facturaDet=new Vector<>();
    private Vector titulos,data=new Vector();
    DefaultTableModel modelo;
    private boolean ins=false,b=false,c=false,a=false;
    private float isv=-1,temp=0,limi=0;;
    private ControlFacturaCab controlfacuraCab=new ControlFacturaCab();
    private ControlFacturaDet controlfacturaDet=new ControlFacturaDet();
    private ControlCliente controlcliente=new ControlCliente();
    private ControlArticulo controlArticulo=new ControlArticulo();
    private Cliente cliente;
    private FacturaCab facturacab;
    private FacturaDet facturadet;
    /**
     * Creates new form frmCompra
     */
    public frmFactura() {
        titulos=new Vector();
        titulos.addElement("ID Articulo");titulos.addElement("Nombre del Articulo");titulos.addElement("Cantidad");
        titulos.addElement("Precio");titulos.addElement("ISV");titulos.addElement("Total");
        initComponents();
        txtCampos.add(txtFacturaID);
        txtCampos.add(txtFecha);
        txtCampos.add(txtClienteID);
        txtCampos.add(txtBodegaID);
        txtCampos.add(txtPrecio);
        txtCampos.add(txtTotalNeto1);
        lblLabels.add(lblNombreArticulo);
        lblLabels.add(lblNombreBodega);
        lblLabels.add(lblNombreCliente);
        lblLabels.add(lblSaldo);
        modelo=(DefaultTableModel) Tabla.getModel();
        Tabla.setModel(modelo);
        facturacab=new FacturaCab();
        txtFecha.setText(controlfacuraCab.getFechaSistema());
        int auto = controlfacuraCab.autoNumerico();
        txtFacturaID.setText(String.valueOf(auto));
        txtClienteID.grabFocus();
    }
    private void Limpiar_Campos(){
        for (JTextField o : txtCampos) {
            o.setText("");
        }
        for (JLabel o : lblLabels) {
            o.setText("");
        }
        txtFecha.setText(controlfacuraCab.getFechaSistema());
        cboEstado.setSelectedIndex(0);
        cboTipo.setSelectedIndex(0);
        ins=false;isv=-1;temp=0;limi=0;
        b=false;c=false;a=false;
        int auto = controlfacuraCab.autoNumerico();
        txtFacturaID.setText(String.valueOf(auto));
        txtClienteID.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtFacturaID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtClienteID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        valid = new javax.swing.JButton();
        cboEstado = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtBodegaID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblNombreBodega = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtArticuloID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lblNombreArticulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnQuitarLinea = new javax.swing.JButton();
        btnAgregarLinea = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtISV = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTotalNeto1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setTitle("Formulario de Facturacion");
        setFrameIcon(null);
        setName("frmFactura"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Encabezado de la Factura"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("No. de Factura :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txtFacturaID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFacturaID.setEnabled(false);
        txtFacturaID.setName("CompraID"); // NOI18N
        jPanel1.add(txtFacturaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Codigo del Cliente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtClienteID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtClienteID.setName("ProveedorID"); // NOI18N
        txtClienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtClienteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Año-Mes-Día");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setEnabled(false);
        txtFecha.setName("Fecha"); // NOI18N
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Estado ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        valid.setText("Validadar");
        valid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validActionPerformed(evt);
            }
        });
        jPanel1.add(valid, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 130, -1));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Facturado", "Anulado" }));
        jPanel1.add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nombre del Cliente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        lblNombreCliente.setBackground(java.awt.Color.white);
        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreCliente.setName("Estado"); // NOI18N
        lblNombreCliente.setOpaque(true);
        jPanel1.add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 270, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Tipo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contado", "Credito" }));
        jPanel1.add(cboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Codigo de Bodega");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtBodegaID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBodegaID.setName("ProveedorID"); // NOI18N
        txtBodegaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodegaIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtBodegaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nombre de la Bodega");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        lblNombreBodega.setBackground(java.awt.Color.white);
        lblNombreBodega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBodega.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreBodega.setName("Estado"); // NOI18N
        lblNombreBodega.setOpaque(true);
        jPanel1.add(lblNombreBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 270, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Saldo del Cliente");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        lblSaldo.setBackground(java.awt.Color.white);
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblSaldo.setName("Estado"); // NOI18N
        lblSaldo.setOpaque(true);
        jPanel1.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 190));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 100, 50));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 100, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de la Factura"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArticuloID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtArticuloID.setName("ArticuloID"); // NOI18N
        txtArticuloID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArticuloIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtArticuloID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Codigo de Articulo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Nombre del Articulo");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setName("Cantidad"); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 100, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Cantidad");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        lblNombreArticulo.setBackground(java.awt.Color.white);
        lblNombreArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreArticulo.setOpaque(true);
        jPanel2.add(lblNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 240, 20));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(data,titulos)
            {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            }
        );
        jScrollPane1.setViewportView(Tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 750, 140));

        btnQuitarLinea.setText("Quitar Linea");
        btnQuitarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarLineaActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuitarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 120, -1));

        btnAgregarLinea.setText("Agregar Linea");
        btnAgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLineaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 120, -1));

        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecio.setEnabled(false);
        txtPrecio.setName("ArticuloID"); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Precio");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        txtISV.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtISV.setEnabled(false);
        txtISV.setName("ArticuloID"); // NOI18N
        txtISV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISVActionPerformed(evt);
            }
        });
        jPanel2.add(txtISV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("ISV");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setEnabled(false);
        txtTotal.setName("ArticuloID"); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 90, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Total");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        txtTotalNeto1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalNeto1.setEnabled(false);
        jPanel2.add(txtTotalNeto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 90, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Total de la Factura");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 770, 270));

        jButton3.setText("Grabar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 100, 50));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-934)/2, (screenSize.height-576)/2, 934, 576);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Limpiar_Campos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtClienteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteIDActionPerformed
        cliente = new Cliente();
        int x=-1;
        try {
            x= Integer.parseInt(txtClienteID.getText());
            cliente=controlcliente.getCliente(x);
            if(cliente!=null){
                lblNombreCliente.setText(cliente.getNombre());
                lblSaldo.setText(cliente.getSaldo());
                limi=inter.String_Float(cliente.getLimite());
                cboTipo.grabFocus();
                c = true;
            }
            else{
                c=false;
                txtClienteID.grabFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe de ingresar un valor numerico", "Error", JOptionPane.ERROR_MESSAGE);
            txtClienteID.grabFocus();
        }
    }//GEN-LAST:event_txtClienteIDActionPerformed

    private void txtArticuloIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArticuloIDActionPerformed
        if (ins) {
            if (!txtArticuloID.getText().isEmpty()) {
                Articulo articulo = new Articulo();
                int x = -1;
                try {
                    x = Integer.parseInt(txtArticuloID.getText());
                    articulo = controlArticulo.seekArticulo(x);
                    if (articulo != null && articulo.getTipo().equals("P")) {
                        lblNombreArticulo.setText(articulo.getNombre());
                        
                        Precio precio=new Precio();
                        ControlPrecio controlprecio=new ControlPrecio();
                        precio=controlprecio.seekPrecio(x, inter.String_Int(cliente.getListaid()));
                        if (precio != null) {
                            txtPrecio.setText(precio.getPrecio()+"");
                        }
                        if(articulo.getISV().equals("1")){
                            isv=Float.parseFloat("0.12");
                        }else if(articulo.getISV().equals("0")){
                            isv=0;
                        }
                        txtCantidad.grabFocus();
                        a=true;
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Debe de ser un Articulo de Producto Terminado", "Error", JOptionPane.ERROR_MESSAGE);
                        txtArticuloID.grabFocus();
                        a=false;
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Debe de ingresar un valor numerico", "Error", JOptionPane.ERROR_MESSAGE);
                    txtArticuloID.grabFocus();
                    a=false;
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"El Campo Articulo ID esta Vacio","Error",JOptionPane.ERROR_MESSAGE);
                txtArticuloID.grabFocus();
                a=false;
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"El encabezado de la Factura no esta validado aun!!!","Error",JOptionPane.ERROR_MESSAGE);
            valid.grabFocus();
        }
    }//GEN-LAST:event_txtArticuloIDActionPerformed

    private void btnQuitarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarLineaActionPerformed
        int x=-1;
        x=Tabla.getSelectedRow();
        if(x<0){
            JOptionPane.showMessageDialog(rootPane, "No se puede debes de seleccionar una linea de la tabla");
        }
        else{
            temp=temp- Float.valueOf(modelo.getValueAt(x, 5).toString());
            txtTotal.setText(temp+"");
            facturaDet.remove(x);
            modelo.removeRow(x);
            txtArticuloID.setText("");
            txtCantidad.setText("");
            lblNombreArticulo.setText("");
            txtCantidad.setText("");
            txtPrecio.setText("");
            txtISV.setText("");
            txtTotal.setText("");
            txtArticuloID.grabFocus();
            b=false;a=false;
        }
    }//GEN-LAST:event_btnQuitarLineaActionPerformed

    private void btnAgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLineaActionPerformed
        if((txtArticuloID.getText().isEmpty()) || (txtCantidad.getText().isEmpty())){
            JOptionPane.showMessageDialog(rootPane, "No se puede ingresar linea con campos vacios");
        }
        else if(a==false){
            JOptionPane.showMessageDialog(rootPane, "No se puede ingresar linea con campo Articulo sin validar");
            txtArticuloID.grabFocus();
        }
        else if(b==false){
            JOptionPane.showMessageDialog(rootPane, "No se puede ingresar linea con campo Cantidad sin validar");
            txtCantidad.grabFocus();
        }
        else{
            float sal=inter.String_Float(cliente.getSaldo());
            temp = temp + Float.valueOf(txtTotal.getText());
            if ((Float.parseFloat(lblSaldo.getText())+temp) <= limi && cboTipo.getSelectedIndex()==1) {
                Vector rou = new Vector();
                rou.addElement(txtArticuloID.getText().toUpperCase());
                rou.addElement(lblNombreArticulo.getText().toUpperCase());
                rou.addElement(txtCantidad.getText());
                rou.addElement(txtPrecio.getText());
                rou.addElement(txtISV.getText());
                rou.addElement(txtTotal.getText());

                int c1 = -1, c2 = -1, c3 = -1;
                float f1=0,f2=0;

                c1 = inter.String_Int(txtFacturaID.getText());
                c2 = inter.String_Int(txtArticuloID.getText());
                c3 = Integer.valueOf(txtCantidad.getText());
                f1 = inter.String_Float(txtPrecio.getText());
                f2 = inter.String_Float(txtISV.getText());

                facturadet = new FacturaDet(c1, c2, c3, f1, f2);
                facturaDet.addElement(facturadet);
                txtTotalNeto1.setText(temp+"");
                modelo.addRow(rou);
            }
            else if ((Float.parseFloat(lblSaldo.getText())+temp) > limi && cboTipo.getSelectedIndex()==0) {
                Vector rou = new Vector();
                rou.addElement(txtArticuloID.getText().toUpperCase());
                rou.addElement(lblNombreArticulo.getText().toUpperCase());
                rou.addElement(txtCantidad.getText());
                rou.addElement(txtPrecio.getText());
                rou.addElement(txtISV.getText());
                rou.addElement(txtTotal.getText());

                int c1 = -1, c2 = -1, c3 = -1;
                float f1=0,f2=0;

                c1 = inter.String_Int(txtFacturaID.getText());
                c2 = inter.String_Int(txtArticuloID.getText());
                c3 = Integer.valueOf(txtCantidad.getText());
                f1 = inter.String_Float(txtPrecio.getText());
                f2 = inter.String_Float(txtISV.getText());

                facturadet = new FacturaDet(c1, c2, c3, f1, f2);
                facturaDet.addElement(facturadet);
                txtTotalNeto1.setText(temp+"");
                modelo.addRow(rou);
            }
            else{
                float c=(Float.parseFloat(lblSaldo.getText())+temp) - limi;
                JOptionPane.showMessageDialog(rootPane,"No se puede agregar linea por que se excede\n limite con el Cliente por cantidad de "+c);
                temp=temp- Float.valueOf(txtTotal.getText());
                txtTotalNeto1.setText(temp+"");
            }
            txtArticuloID.setText("");
            txtCantidad.setText("");
            lblNombreArticulo.setText("");
            txtCantidad.setText("");
            txtPrecio.setText("");
            txtISV.setText("");
            txtTotal.setText("");
            txtArticuloID.grabFocus();
            b=false;a=false;
        }
    }//GEN-LAST:event_btnAgregarLineaActionPerformed

    private void validActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validActionPerformed
        if(!c){
            JOptionPane.showMessageDialog(rootPane,"Campo Codigo del Cliente no esta validado","Error",JOptionPane.ERROR_MESSAGE);
            txtClienteID.grabFocus();
        }else if(!b){
            JOptionPane.showMessageDialog(rootPane,"Campo Codigo de la Bodega no esta validado","Error",JOptionPane.ERROR_MESSAGE);
            txtBodegaID.grabFocus();
        }
        else{
            String qq="",qq1="";
            if(cboEstado.getSelectedIndex()==0){
                qq="F";
            }
            if(cboTipo.getSelectedIndex()==0){
                qq1="C";
            }else{
                qq1="R";
            }
            facturacab=new FacturaCab(inter.String_Int(txtFacturaID.getText()),inter.String_Int(txtClienteID.getText()),txtFecha.getText(),qq1,qq,inter.String_Int(txtBodegaID.getText()));
            ins=true;
            txtArticuloID.grabFocus();
        }
    }//GEN-LAST:event_validActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!ins){
            JOptionPane.showMessageDialog(rootPane,"El encabezado de la Factura no esta validado aun!!!","Error",JOptionPane.ERROR_MESSAGE);
            valid.grabFocus();
        }
        else if(modelo.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, "No se han ingresado Articulos en el detalle del Pedido");
            txtArticuloID.grabFocus();
        }
        else{
            int res=JOptionPane.showConfirmDialog(rootPane,"¿Desea GRABAR ESTA FACTURA?","PREGUNTA",JOptionPane.YES_NO_OPTION);
            if(res==JOptionPane.YES_OPTION){
                boolean y=controlfacuraCab.insFacturaCab(facturacab);
                if (facturacab.getTipo().equals("R")) {
                    float sal = inter.String_Float(cliente.getSaldo());
                    cliente.setSaldo((sal + Float.parseFloat(txtTotalNeto1.getText())) + "");
                    controlcliente.updCliente(cliente);
                }
                boolean x=false;
                for(FacturaDet o:facturaDet){
                    x=controlfacturaDet.insFacturaDet(o,facturacab);
                    if(!x){
                        break;
                    }
                }
                if((y) && (x)){
                    JOptionPane.showMessageDialog(rootPane, "FACTURA GRABADADO CON EXITO");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "HUBO PROBLEMAS AL MOMENTO DE REGISTRAR LA FACTURA");
                }
                txtArticuloID.setText("");
                txtCantidad.setText("");
                lblNombreArticulo.setText("");
                facturaDet.clear();
                for(int e=modelo.getRowCount()-1;e>-1;e--){
                    modelo.removeRow(e);
                }
                Limpiar_Campos();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed

    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtBodegaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodegaIDActionPerformed
        Bodega bodega = new Bodega();
        int x=-1;
        try {
            x= Integer.parseInt(txtBodegaID.getText());
            bodega=new ControlBodega().seekBodega(x);
            if(bodega!=null){
                lblNombreBodega.setText(bodega.getNombre());
                cboEstado.grabFocus();
                b = true;
            }
            else{
                b=false;
                txtBodegaID.grabFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe de ingresar un valor numerico", "Error", JOptionPane.ERROR_MESSAGE);
            txtBodegaID.grabFocus();
        }
    }//GEN-LAST:event_txtBodegaIDActionPerformed

    private void txtISVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISVActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        float p,c,i,t;
        String isv1, tot;
        Existencia exis=new Existencia();
        ControlExistencia control = new ControlExistencia();
        exis = control.seekExistencia1(facturacab.getBodegaID(), inter.String_Int(txtArticuloID.getText()));
        if (exis.getCantidad() >= Integer.valueOf(txtCantidad.getText())) {
            p = Float.valueOf(txtPrecio.getText());
            c = Float.valueOf(txtCantidad.getText());
            i = Float.valueOf(isv);
            isv1 = String.valueOf(p * c * i);
            t = (p * c) + (p * c * i);
            tot = String.valueOf(t);
            txtISV.setText(isv1);
            txtTotal.setText(tot);
            b = true;
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"La cantidad debe de ser menor que las Existencias en el sistema","ERROR",JOptionPane.ERROR_MESSAGE);
            b = false;
            txtCantidad.grabFocus();
        }
        
    }//GEN-LAST:event_txtCantidadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnAgregarLinea;
    private javax.swing.JButton btnQuitarLinea;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreArticulo;
    private javax.swing.JLabel lblNombreBodega;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtArticuloID;
    private javax.swing.JTextField txtBodegaID;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtClienteID;
    private javax.swing.JTextField txtFacturaID;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtISV;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalNeto1;
    private javax.swing.JButton valid;
    // End of variables declaration//GEN-END:variables
}
