package View;
import Controller.*;
import Model.Articulo;
import Model.ModeloCab;
import Model.ModeloDet;
import Utilerias.interfacex;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author root4142
 */
public class frmModelo extends javax.swing.JInternalFrame {
    private interfacex inter=new interfacex();
    private Vector<JTextField> txtCampos=new Vector<>();
    private Vector<JLabel> lblLabels=new Vector<>();
    private Vector<ModeloDet> modeloDet=new Vector<>();
    private Vector titulos,data=new Vector();
    DefaultTableModel modelo;
    private boolean val=false,b=false,a=false,ins=true;
    private ControlModeloCab controlmodeloCab=new ControlModeloCab();
    private ControlModeloDet controlmodeloDet=new ControlModeloDet();
    private ControlArticulo controlArticulo=new ControlArticulo();
    private ModeloCab modelocab;
    private ModeloDet modelodet;
    /**
     * Creates new form frmCompra
     */
    public frmModelo() {
        titulos=new Vector();
        titulos.addElement("ID Articulo");titulos.addElement("Nombre del Articulo");titulos.addElement("Cantidad");
        initComponents();
        txtCampos.add(txtCantidadM);
        txtCampos.add(txtNombre);
        txtCampos.add(txtArticuloID1);
        lblLabels.add(lblNombreArticuloEnc);
        lblLabels.add(lblNombreArticulo);
        modelo=(DefaultTableModel) Tabla.getModel();
        Tabla.setModel(modelo);
        modelocab=new ModeloCab();
        int auto = controlmodeloCab.autoNumerico();
        txtModeloID.setText(String.valueOf(auto));
        txtNombre.grabFocus();
    }
    private void Limpiar_Campos(){
        for (JTextField o : txtCampos) {
            o.setText("");
        }
        for (JLabel o : lblLabels) {
            o.setText("");
        }
        cboEstado.setSelectedIndex(0);
        val=false;ins=true;
        b=false;a=false;
        modeloDet.clear();
        int auto = controlmodeloCab.autoNumerico();
        txtModeloID.setText(String.valueOf(auto));
        txtNombre.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtArticuloID1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblNombreArticuloEnc = new javax.swing.JLabel();
        valid = new javax.swing.JButton();
        txtModeloID = new javax.swing.JTextField();
        cboEstado = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtArticuloID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lblNombreArticulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnQuitarLinea = new javax.swing.JButton();
        btnAgregarLinea = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setTitle("Formulario de Asignacion de Modelos de Articulos Procesados.");
        setFrameIcon(null);
        setName("frmModelo"); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Encabezado del Modelo."));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("No. de Modelo :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        txtCantidadM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidadM.setName("CompraID"); // NOI18N
        jPanel1.add(txtCantidadM, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Codigo del Articulo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtArticuloID1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtArticuloID1.setName("ProveedorID"); // NOI18N
        txtArticuloID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArticuloID1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtArticuloID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nombre del Articulo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Cantidad :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nombre del Modelo :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setName("Fecha"); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 290, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Estado del Modelo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        lblNombreArticuloEnc.setBackground(java.awt.Color.white);
        lblNombreArticuloEnc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreArticuloEnc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreArticuloEnc.setName("Estado"); // NOI18N
        lblNombreArticuloEnc.setOpaque(true);
        jPanel1.add(lblNombreArticuloEnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 270, 30));

        valid.setText("Validadar");
        valid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validActionPerformed(evt);
            }
        });
        jPanel1.add(valid, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 130, -1));

        txtModeloID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtModeloID.setEnabled(false);
        txtModeloID.setName("CompraID"); // NOI18N
        jPanel1.add(txtModeloID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 90, -1));

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 150, -1));

        jButton4.setText("Recuperar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 200));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 100, 50));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 100, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle del Pedido."));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArticuloID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtArticuloID.setName("ArticuloID"); // NOI18N
        txtArticuloID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArticuloIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtArticuloID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Codigo de Articulo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Nombre del Articulo");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setName("Cantidad"); // NOI18N
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 100, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Cantidad");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        lblNombreArticulo.setBackground(java.awt.Color.white);
        lblNombreArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNombreArticulo.setOpaque(true);
        jPanel2.add(lblNombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 240, 30));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(data,titulos)
            {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            }
        );
        jScrollPane1.setViewportView(Tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 860, 160));

        btnQuitarLinea.setText("Quitar Linea");
        btnQuitarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarLineaActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuitarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, -1));

        btnAgregarLinea.setText("Agregar Linea");
        btnAgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLineaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 890, 310));

        jButton3.setText("Grabar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 100, 50));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-926)/2, (screenSize.height-639)/2, 926, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Limpiar_Campos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtArticuloID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArticuloID1ActionPerformed
        Articulo articulo = new Articulo();
        int x=-1;
        try {
            x= Integer.parseInt(txtArticuloID1.getText());
            articulo=controlArticulo.seekArticulo(x);
            if(articulo!=null && articulo.getTipo().equals("P")){
                lblNombreArticuloEnc.setText(articulo.getNombre());
                txtCantidadM.grabFocus();
                a = true;
            }
            else{
                a=false;
                JOptionPane.showMessageDialog(rootPane, "Debe de ser un Articulo de Producto Procesado", "Error", JOptionPane.ERROR_MESSAGE);
                txtArticuloID1.grabFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe de ingresar un valor numerico", "Error", JOptionPane.ERROR_MESSAGE);
            txtArticuloID1.grabFocus();
        }
    }//GEN-LAST:event_txtArticuloID1ActionPerformed

    private void txtArticuloIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArticuloIDActionPerformed
        if (val) {
            if (!txtArticuloID.getText().isEmpty()) {
                Articulo articulo = new Articulo();
                int x = -1;
                try {
                    x = Integer.parseInt(txtArticuloID.getText());
                    articulo = controlArticulo.seekArticulo(x);
                    if (articulo != null && articulo.getTipo().equals("T")) {
                        lblNombreArticulo.setText(articulo.getNombre());
                        txtCantidad.grabFocus();
                        b=true;
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Debe de ser un Articulo de materia Prima", "Error", JOptionPane.ERROR_MESSAGE);
                        txtArticuloID.grabFocus();
                        b=false;
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Debe de ingresar un valor numerico", "Error", JOptionPane.ERROR_MESSAGE);
                    txtArticuloID.grabFocus();
                    b=false;
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"El Campo Articulo ID esta Vacio","Error",JOptionPane.ERROR_MESSAGE);
                txtArticuloID.grabFocus();
                b=false;
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"El encabezado del Modelo no esta validado aun!!!","Error",JOptionPane.ERROR_MESSAGE);
            valid.grabFocus();
        }
    }//GEN-LAST:event_txtArticuloIDActionPerformed

    private void btnQuitarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarLineaActionPerformed
        int x=-1;
        x=Tabla.getSelectedRow();
        if(x<0){
            JOptionPane.showMessageDialog(rootPane, "No se puede debes de seleccionar una linea de la tabla");
        }
        else{
            modeloDet.remove(x);
            modelo.removeRow(x);
            txtArticuloID.setText("");txtCantidad.setText("");
            lblNombreArticulo.setText("");
            txtArticuloID.grabFocus();
        }
    }//GEN-LAST:event_btnQuitarLineaActionPerformed

    private void btnAgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLineaActionPerformed
        if((txtArticuloID.getText().isEmpty()) || (txtCantidad.getText().isEmpty())){
            JOptionPane.showMessageDialog(rootPane, "No se puede ingresar linea con campos vacios");
        }
        else if(b==false){
            JOptionPane.showMessageDialog(rootPane, "No se puede ingresar linea con campo Articulo de Materia Prima sin validar");
            txtArticuloID.grabFocus();
        }
        else{
            Vector rou = new Vector();
            rou.addElement(txtArticuloID.getText().toUpperCase());
            rou.addElement(lblNombreArticulo.getText().toUpperCase());
            rou.addElement(txtCantidad.getText());

            int c1 = -1, c2 = -1, c3 = -1;

            c1 = inter.String_Int(txtModeloID.getText());
            c2 = inter.String_Int(txtArticuloID.getText());
            c3 = Integer.valueOf(txtCantidad.getText());

            modelodet = new ModeloDet(c1, c2, c3);
            modeloDet.addElement(modelodet);
            modelo.addRow(rou);

            txtArticuloID.setText("");
            txtCantidad.setText("");
            lblNombreArticulo.setText("");
            txtArticuloID.grabFocus();
            b=false;
        }
    }//GEN-LAST:event_btnAgregarLineaActionPerformed

    private void validActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validActionPerformed
        if(!a){
            JOptionPane.showMessageDialog(rootPane,"Campo Codigo del Articulo no esta validado","Error",JOptionPane.ERROR_MESSAGE);
            txtArticuloID1.grabFocus();
        }
        else if(txtCantidadM.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Campo Cantidad del Articulo no esta validado","Error",JOptionPane.ERROR_MESSAGE);
            txtCantidadM.grabFocus();
        }
        else{
            String e="";
            if(cboEstado.getSelectedIndex()==0){
                e="A";
            }else{
                e="I";
            }
            modelocab=new ModeloCab(inter.String_Int(txtModeloID.getText()),txtNombre.getText().toUpperCase(),inter.String_Int(txtArticuloID1.getText()),inter.String_Int(txtCantidadM.getText()),e);
            val=true;
            txtArticuloID.grabFocus();
        }
    }//GEN-LAST:event_validActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!val){
            JOptionPane.showMessageDialog(rootPane,"El encabezado del Modelo no esta validado aun!!!","Error",JOptionPane.ERROR_MESSAGE);
            valid.grabFocus();
        }
        else if(modelo.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, "No se han ingresado Articulos de Materia Prima en el detalle del Modelo");
            txtArticuloID.grabFocus();
        }
        else{
            int res=JOptionPane.showConfirmDialog(rootPane,"¿Desea GRABAR ESTE MODELO?","PREGUNTA",JOptionPane.YES_NO_OPTION);
            if(res==JOptionPane.YES_OPTION){
                boolean y = false;
                boolean x = false;
                if(ins){
                    y = controlmodeloCab.insModeloCab(modelocab);
                    for (ModeloDet o : modeloDet) {
                        x = controlmodeloDet.insModeloDet(o);
                        if (!x) {
                            break;
                        }
                    }
                }else{
                    y=controlmodeloCab.updModeloCab(modelocab);
                    controlmodeloDet.delModeloDet(modelocab);
                    for (ModeloDet o : modeloDet) {
                        x = controlmodeloDet.insModeloDet(o);
                        if (!x) {
                            break;
                        }
                    }
                }
                if((y) && (x)){
                    JOptionPane.showMessageDialog(rootPane, "MODELO GRABADADO CON EXITO");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "HUBO PROBLEMAS AL MOMENTO DE REGISTRAR EL MODELO");
                }
                txtArticuloID.setText("");
                txtCantidad.setText("");
                lblNombreArticulo.setText("");
                lblNombreArticuloEnc.setText("");
                modeloDet.clear();
                for(int e=modelo.getRowCount()-1;e>-1;e--){
                    modelo.removeRow(e);
                }
                Limpiar_Campos();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int x = -1;
        try {
            x = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese No. del Modelo : ", "Ingrese", JOptionPane.INFORMATION_MESSAGE));
            modelocab = new ModeloCab();
            modelocab = controlmodeloCab.seekModeloCab(x);
            if (modelocab != null) {
                txtModeloID.setText(modelocab.getModeloID() + "");
                txtNombre.setText(modelocab.getNombre() + "");
                txtArticuloID1.setText(modelocab.getArticuloID() + "");
                txtArticuloID1ActionPerformed(evt);
                txtCantidadM.setText(modelocab.getCantidad() + "");
                if (modelocab.getEstado().equals("A")) {
                    cboEstado.setSelectedIndex(0);
                } else if (modelocab.getEstado().equals("I")) {
                    cboEstado.setSelectedIndex(1);
                }
                validActionPerformed(evt);
                Vector<ModeloDet> modeloDet1=new Vector<>();
                modeloDet.clear();
                modeloDet1 = controlmodeloDet.seekModeloDetVector(x);
                if (!modeloDet1.isEmpty()) {
                    System.out.println(modeloDet1.size());
                    for (ModeloDet oo : modeloDet1) {
                        modelodet = new ModeloDet();
                        modelodet = oo;
                        txtArticuloID.setText(modelodet.getArticuloID() + "");
                        txtArticuloIDActionPerformed(evt);
                        txtCantidad.setText(modelodet.getCantidad() + "");
                        btnAgregarLineaActionPerformed(evt);
                    }
                }
            val = false;
            b = false;
            a = false;
            ins = false;
            txtNombre.grabFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Debe de ingresar un No. de Modelo Valido", "Error_RECOVERY", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnAgregarLinea;
    private javax.swing.JButton btnQuitarLinea;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreArticulo;
    private javax.swing.JLabel lblNombreArticuloEnc;
    private javax.swing.JTextField txtArticuloID;
    private javax.swing.JTextField txtArticuloID1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadM;
    private javax.swing.JTextField txtModeloID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JButton valid;
    // End of variables declaration//GEN-END:variables
}
