/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JInternalFrame;

/**
 *
 * @author root4142
 */
public class MDI extends javax.swing.JFrame {
private JInternalFrame[] all;
    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem29 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jMenu1.setText("Inventario");

        jMenuItem4.setText("Bodega");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem6.setText("Categoria");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Articulo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);
        jMenu1.add(jSeparator4);

        jMenuItem22.setText("Ingreso de Materia Prima");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem22);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ventas");

        jMenuItem8.setText("Lista");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Clientes");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);
        jMenu3.add(jSeparator3);

        jMenuItem14.setText("Asignar Precios");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuItem21.setText(" Facturacion");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem21);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Produccion");

        jMenuItem15.setText("Modelo de Articulo Procesado");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);
        jMenu4.add(jSeparator2);

        jMenuItem10.setText("Pedido a Produccion");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem16.setText("Orden de produccion");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);
        jMenu4.add(jSeparator6);

        jMenuItem26.setText("Actualizar Estado de la Orden");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem26);

        jMenuItem27.setText("Actualizar Estado del Pedido");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem27);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Compras");

        jMenuItem5.setText("Proveedores");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);
        jMenu5.add(jSeparator1);

        jMenuItem19.setText("Requisiciones para Compras");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem19);

        jMenuItem20.setText(" Compra de materia prima");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem20);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Consultas");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Existencia de Articulos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem11.setText("Existencia de Productos por Bodega");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem13.setText("Existencia de Materia Prima por Bodega");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);
        jMenu2.add(jSeparator5);

        jMenuItem23.setText("Materiales del Modelo de Articulo");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem23);

        jMenuItem12.setText("Pedidos en Espera");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem28.setText("Pedidos Procesados");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem28);

        jMenuItem17.setText("Ordenes en espera");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Ordenes procesadas");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);
        jMenu2.add(jSeparator7);

        jMenuItem24.setText("Requisiciones Pendiente de Surtido");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem24);

        jMenuItem25.setText("Compras por Proveedor");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem25);
        jMenu2.add(jSeparator8);

        jMenuItem29.setText("Saldo de Clientes ");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem29);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
           frmBodega b= new frmBodega();
           this.escritorio.add(b);
           escritorio.setSelectedFrame(b);
           b.show();b.toFront();
        }
        else {
            int t=0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmBodega")) {
                    escritorio.setSelectedFrame(x);
                    t=-1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmBodega b = new frmBodega();
                this.escritorio.add(b, javax.swing.JLayeredPane.DEFAULT_LAYER);
                escritorio.setSelectedFrame(b);
                b.show();
                b.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmProveedor Pr = new frmProveedor();
            this.escritorio.add(Pr);
            escritorio.setSelectedFrame(Pr);
            Pr.show();
            Pr.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmProveedor")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmProveedor Pr = new frmProveedor();
                this.escritorio.add(Pr);
                escritorio.setSelectedFrame(Pr);
                Pr.show();
                Pr.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
           frmCategoria Ct= new frmCategoria();
           this.escritorio.add(Ct);
           escritorio.setSelectedFrame(Ct);
           Ct.show();Ct.toFront();
        }
        else {
            int t=0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmCategoria")) {
                    escritorio.setSelectedFrame(x);
                    t=-1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmCategoria Ct= new frmCategoria();
                this.escritorio.add(Ct);
                this.escritorio.add(Ct, javax.swing.JLayeredPane.DEFAULT_LAYER);
                Ct.show();Ct.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
           frmArticulo Art= new frmArticulo();
           this.escritorio.add(Art);
           escritorio.setSelectedFrame(Art);
           Art.show();Art.toFront();
        }
        else {
            int t=0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmArticulo")) {
                    escritorio.setSelectedFrame(x);
                    t=-1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmArticulo Art = new frmArticulo();
                this.escritorio.add(Art);
                escritorio.setSelectedFrame(Art);
                Art.show();
                Art.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmLista41 Lst= new frmLista41();
           this.escritorio.add(Lst);
           escritorio.setSelectedFrame(Lst);
           Lst.show();Lst.toFront();
        }
        else {
            int t=0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmLista41")) {
                    escritorio.setSelectedFrame(x);
                    t=-1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmLista41 Lst= new frmLista41();
           this.escritorio.add(Lst);
           escritorio.setSelectedFrame(Lst);
           Lst.show();Lst.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
           frmCliente41 Clt= new frmCliente41();
           this.escritorio.add(Clt);
           escritorio.setSelectedFrame(Clt);
           Clt.show();Clt.toFront();
        }
        else {
            int t=0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmCliente41")) {
                    escritorio.setSelectedFrame(x);
                    t=-1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmCliente41 Clt= new frmCliente41();
                this.escritorio.add(Clt);
                escritorio.setSelectedFrame(Clt);
                Clt.show();Clt.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmExistencia Ext = new frmExistencia();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmExistencia")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmExistencia Ext = new frmExistencia();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmPedido Ext = new frmPedido();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmPedido")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmPedido Ext = new frmPedido();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmConArticuloBod Ext = new frmConArticuloBod();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmConArticuloBod")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmConArticuloBod Ext = new frmConArticuloBod();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmConPedidoEnEspera Ext = new frmConPedidoEnEspera();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmConPedidoEnEspera")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmConPedidoEnEspera Ext = new frmConPedidoEnEspera();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmConMateriaBod Ext = new frmConMateriaBod();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmConMateriaBod")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmConMateriaBod Ext = new frmConMateriaBod();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
           frmPrecio Ext = new frmPrecio();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        }
        else {
            int t=0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmPrecio")) {
                    escritorio.setSelectedFrame(x);
                    t=-1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmPrecio Ext = new frmPrecio();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmModelo Ext = new frmModelo();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmModelo")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmModelo Ext = new frmModelo();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmOrden Ext = new frmOrden();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmOrden")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmOrden Ext = new frmOrden();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmConOrdenEnEspera Ext = new frmConOrdenEnEspera();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmConOrdenEnEspera")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmConOrdenEnEspera Ext = new frmConOrdenEnEspera();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmConOrdenProcesados Ext = new frmConOrdenProcesados();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmConOrdenProcesados")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmConOrdenProcesados Ext = new frmConOrdenProcesados();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmRequisicion Ext = new frmRequisicion();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmRequisicion")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmRequisicion Ext = new frmRequisicion();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmCompra Ext = new frmCompra();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmCompra")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmCompra Ext = new frmCompra();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmConModelo Ext = new frmConModelo();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmConModelo")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmConModelo Ext = new frmConModelo();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmConRequisicionEspera Ext = new frmConRequisicionEspera();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmConRequisicionEspera")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmConRequisicionEspera Ext = new frmConRequisicionEspera();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmConComprasProveedor Ext = new frmConComprasProveedor();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmConComprasProveedor")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmConComprasProveedor Ext = new frmConComprasProveedor();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmIngreso Ext = new frmIngreso();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        }
        else {
            int t=0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmIngreso")) {
                    escritorio.setSelectedFrame(x);
                    t=-1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmIngreso Ext = new frmIngreso();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmOrdenActualiza Ext = new frmOrdenActualiza();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmOrdenActualiza")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmOrdenActualiza Ext = new frmOrdenActualiza();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmPedidoActualiza Ext = new frmPedidoActualiza();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmPedidoActualiza")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmPedidoActualiza Ext = new frmPedidoActualiza();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmConPedidoEnProcesados Ext = new frmConPedidoEnProcesados();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmConPedidoEnProcesados")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmConPedidoEnProcesados Ext = new frmConPedidoEnProcesados();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmFactura Ext = new frmFactura();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        }
        else {
            int t=0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmFactura")) {
                    escritorio.setSelectedFrame(x);
                    t=-1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmFactura Ext = new frmFactura();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        all = escritorio.getAllFrames();
        if (all.length == 0) {
            frmConSaldoCliente Ext = new frmConSaldoCliente();
            this.escritorio.add(Ext);
            escritorio.setSelectedFrame(Ext);
            Ext.show();
            Ext.toFront();
        } else {
            int t = 0;
            for (JInternalFrame x : all) {
                if (x.getName().equals("frmConSaldoCliente")) {
                    escritorio.setSelectedFrame(x);
                    t = -1;
                    x.toFront();
                }
            }
            if (t != -1) {
                frmConSaldoCliente Ext = new frmConSaldoCliente();
                this.escritorio.add(Ext);
                escritorio.setSelectedFrame(Ext);
                Ext.show();
                Ext.toFront();
            }
        }
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
